### ISSUE TITLE
When ReachableTask decides that a device is unreachable, all further tasks need to be stopped

### ISSUE THREAD

**Issue by lunkwill42** [Uninett/zino#108]
We have chosen to split Zino 2's work into multiple tasks that run in serial, so they can be neatly and conceptually separate.  However, the `ReachableTask` always runs first, and if it decides that a device isn't reachable, it should have some way to signal to the task-running-loop that the remaining tasks can be cancelled.

Right now, the logs fill up with TimeoutErrors for the remaining tasks every time a device is unreachable.

A quick suggestions might be to raise some sort of exception after scheduling the extra reachability checks, like a `DeviceUnreachableError`  or something.

**Comment by stveit** [comment]
Made something in #124 but not sure if im all too happy with it

**Comment by lunkwill42** [comment]
> A device being unreachable does not cause the RreachableTask to not be able to complete its purpose, because handling a device being unreachable IS the purpose. So raising an exception does not really make sense.

Well, I tend to disagree.  The purpose of `ReachableTask` is to verify that a device is reachable.  When a device isn't, that is an exceptional situation, and there is nothing wrong with using exceptions for flow control in my mind.
