### ISSUE TITLE
Not report cases in closed state when a new clients connects 

### ISSUE THREAD

**Issue by runborg** [Uninett/zino#187]
This is a inconsistency between zino1 and zino2.
When a new client connects to the zino2 server, do not expose the client for cases in closed state.

The list reported by the `caseids` should only include active cases, all cases in closed state should be "hidden" when using this command.

**Comment by lunkwill42** [comment]
> When a new client connects to the zino2 server, do not expose the client for cases in closed state.

This gave me a hangup on the definition "new client".  It made me think that the closed event should still be visible to the client that closed it, but that's not the case.  The issue here is simply that the `CASEIDS` API command should never return the event ID of an event in the `closed` state.
