### ISSUE TITLE
User should not be able to modify objects in closed state

### ISSUE THREAD

**Issue by runborg** [Uninett/zino#188]
This is a inconsistency between zino1 and zino2.
in zino1, when a case is in closed state it is complely locked for editing.

In zino2 when a ticket is in closed state the user should not be able to modify it. eg. adding history.
There could be a discussion on if it should be possible to reopen a case at all. 
There are instances where reopening a case could be beneficial, eg when closing a case by accident eg. by a mass-update.
But this again could make things like triggering an external action when closing cases more difficult as the close action could be done multiple times on a case object.

**Comment by johannaengland** [comment]
I might be mistaken (or confused by TCL), but the only thing that you cannot do in Zino1.0 with closed events is reopening them, but adding history for example should still work.

**Comment by lunkwill42** [comment]
> I might be mistaken (or confused by TCL), but the only thing that you cannot do in Zino1.0 with closed events is reopening them, but adding history for example should still work.

I just checked, and I concur. Zino1 allows adding history to closed events, but will disallow resetting state after it has been set to closed.
