### ISSUE TITLE
BFD: missing attribute neigh_rdns

### ISSUE THREAD

**Issue by runborg** [Uninett/zino#199]
The attribute `neigh_rdns` should include "reverse dns" information of the BFD neighbor. (reverse dns of the address in the bfdaddr field i think)

the zino1 server is not consistent on this field on all types containing ipv4/ipv6 neighbor info, but this could certanly also be done on eg. BGP alarms.

This field is not critical for eg. curitz to function at this state

**Comment by lunkwill42** [comment]
Question: The original codebase seems to call the field `Neigh-rDNS`, not `neigh_rdns`.   Does the difference matter to any existing clients?

**Comment by runborg** [comment]
Ah, it might be that i've miss-spelled it.. it is used both in x11-ritz and in [curitz](https://github.com/Uninett/curitz/blob/d562c4aebad9873b35201087ca793d74c0a5e26e/src/curitz/cli.py#L576), it might be that zinolib / curitz translates `-` to `_` in the attributes to be allowed used as properties directly.

**Comment by runborg** [comment]
yea, it is rewritten.. 
[zino 1](https://github.com/Uninett/zinolib/blob/970cc681e266cf5d038a70181d1b95a7a0044bbf/src/zinolib/controllers/zino1.py#L352-L353)
[zino 0.10](https://github.com/Uninett/zinolib/blob/d3d28c620fd6ed3da136e348e13a73d5e78b9ccc/src/zinolib/ritz.py#L596)

**Comment by runborg** [comment]
so as to also support the original X11 client it needs to have its original name: `Neigh-rDNS`

**Comment by stveit** [comment]
Naming in regards to hyphens and case sensitivity is now handled in #281
