### ISSUE TITLE
Find replacement for tcl string_match

### ISSUE THREAD

**Issue by stveit** [Uninett/zino#207]
`fnmatch` seems like a good candidate. Should talk with håvard eidnes if this would be a suitable replacement

`string_match` doc: https://wiki.tcl-lang.org/page/string+match

`fnmatch` doc: https://docs.python.org/3/library/fnmatch.html

**Comment by lunkwill42** [comment]
`fnmatch` does indeed sound suitable.  I doubt we can find a 100% compatible pattern matcher, but I don't think it's given that we *must* be 100% compatible, as I don't think the PM feature sees that much use, other than from automated scripts that can easily be updates.  Have a quick chat with Håvard and get the issue out of the way :)

**Comment by stveit** [comment]
Mr Zino agrees `fnmatch` should do the trick, so closing this, and will reopen if it doesnt work out
