### ISSUE TITLE
Zino API should not listen to just 127.0.0.1

### ISSUE THREAD

**Issue by lunkwill42** [Uninett/zino#225]
This is a left-over thing from alpha development and should fixed in time for the next release.  Currently, the API is hardcoded to listen only to the `127.0.0.1`, the IPv4 loopback, which makes it unusable outside the server it is running on.

It should really listen to `0.0.0.0` by default (although IPv6 should also be supported).  A command line option should be added to force the daemon to use another address (for testing and development, you might want to force it to use just 127.0.0.1 as it currently does).

**Comment by runborg** [comment]
What about making this api socket binding also configurable in config file ?

**Comment by lunkwill42** [comment]
> What about making this api socket binding also configurable in config file ?

Yes, when the config file stuff is merged, definitely.
