### ISSUE TITLE
Possible wrong value used for port matching in planned maintenance

### ISSUE THREAD

**Issue by stveit** [Uninett/zino#297]
Looking through the OG zino1 code, it uses `$portToLocIfDescr` for matching against ports. I think that might contain `ifalias` values, while `$portToIfDescr` contains `ifdescr`. The PM code right now uses `port.ifdescr` for matching, but maybe it should be changed to `port.ifalias`?

**Comment by stveit** [comment]
`$portToIfDescr`(aka ifdescr) seems to be used for `intf-regexp` matching, while `$portToLocIfDescr` seems to be used for `str` and `regexp` matching

**Comment by stveit** [comment]
https://gitlab.sikt.no/verktoy/zino/-/blob/master/zino/pm.tcl?ref_type=heads#L332

**Comment by lunkwill42** [comment]
Yes, just want to concur that this analysis seems correct.  For reference, `$portToLocIfDescr` is the internal data structure of Zino 1 that holds `ifAlias` values (as in 30 years ago, `ifAlias` did not exist in MIB-II, and Cisco had a proprietary MIB where this object was called `locIfDescr`, until `ifAlias` was standardized in the `IF-MIB`).
