### ISSUE TITLE
zino1 protocol: parameter case-sensitive inconsistencies with tcl implementation

### ISSUE THREAD

**Issue by runborg** [Uninett/zino#331]
In the original zino implementation there are a few parameters that use upper-case characters in their names.
Zino2 does not take this into account and only uses lowercase parameter names

This makes the original x11 ritz client crash because it is case-sensitive on its parameter names.
This is identified for the following parameters:
BGP:
* bgpAS
* bgpOS
* remote-AS

BFD:
* Neigh-rDNS
* bfdAddr
* bfdDiscr
* bfdIx
* bfdState

**Comment by runborg** [comment]
PR #335 is tested with the  x11 tcl ritz client and seems to work fine

**Comment by lunkwill42** [comment]
This is related to #281
