### ISSUE TITLE
Persist Zino device state to disk

### ISSUE THREAD

**Issue by johannaengland** [Uninett/zino#35]
Device state should be persisted to a disk file on set intervals (and later, on demand). This state should be loaded from disk whenever the daemon starts up as well. Same as #21, just with device state instead of event state.

**Comment by lunkwill42** [comment]
ATM there is both event state and device state, and these exist as global variables in `zino.state`  There is potentially other state items that are keyed on things like IP addresses as well (e.g. the mapping from IP addresses to routers).

The best course of action might actually be to create some sort of `ZinoState` class (using PyDantic) to hold all the items we want to serialize/deserialize to/from disk.
