### ISSUE TITLE
Make a link state monitor task

### ISSUE THREAD

**Issue by johannaengland** [Uninett/zino#37]
The link state monitor basically:

1. Collects the complete list of all ports on a device, including their link state
2. Detects link state changes since the last collection and makes new events for changed states

### Implementation breakdown

- [x] #69
- [x] #70
- [x] #75
- [x] #77
- [x] #79

**Comment by lunkwill42** [comment]
Noting that the original Zino code collects both `locIfDescr` and `ifAlias` IF-MIB values if available. However, as pointed out by Håvard in a discussion earlier this year, `locIfDescr` has been deprecated for a number of years (remember, Tcl-Zino started in the 90s), and has been supplanted by `ifAlias`.

I.e. we shouldn't need to care about `locIfDescr` at all in Zino 2.

**Comment by lunkwill42** [comment]
Exploratory coding for this issue reveals that more changes are needed to the base SNMP adapter in `zino.snmp.SNMP`.  #69 is one of these.

Also, none of the current walk implementations support more than one walk variable, while the underlying protocol supports asking for more than one variable per request (whether it be GET-NEXT or GET-BULK).  

The link state monitor needs to get a bunch of attributes (i.e. columns) per interface, and the best way to do this SNMP-wise is to do what Zino 1 calls a sparse walk.  To avoid implementing a sparse walk as a bunch of daisy-chained walks of individual columns, a new getbulk-implementation is needed in `zino.snmp.SNMP`.
,

**Comment by lunkwill42** [comment]
I've removed the flapping task from this issue, as the flapping detection algorithm is only relevant to SNMP trap processing, which isn't implemented yet. This issue can therefore be closed, as the active link state monitor is more or less complete.
