### ISSUE TITLE
Make a BGP state monitor task

### ISSUE THREAD

**Issue by lunkwill42** [Uninett/zino#64]

**Comment by johannaengland** [comment]
In Zino 1.0 the BGP check only happens every other/third time the status check is run. In #133 we currently don't have such a constraint. Therefore we should observe later if it needs to be added.

**Comment by lunkwill42** [comment]
> In Zino 1.0 the BGP check only happens every other/third time the status check is run. In #133 we currently don't have such a constraint. Therefore we should observe later if it needs to be added.

Or as Håvard put it, this constraint was placed in Zino for precautionary reasons, in an attempt to avoid overloading the routers with SNMP requests. Whether this was a real concern has never been tested in practice, so it was suggested we leave it out of Zino 2 and see what happens - and if it's observed to be a real problem, we can re-implement the same precaution in Zino 2.
