### ISSUE TITLE
Make a BFD monitor task

### ISSUE THREAD

**Issue by lunkwill42** [Uninett/zino#65]
Subtasks:

- [x] #86 
- [x] #126

**Comment by lunkwill42** [comment]
Håvard has indicated dissatisfaction with the current BFD monitor in Zino 1.  He should be consulted to design a better implementation for Zino 2.0

**Comment by stveit** [comment]
A juniper implementation has been made (#86), Cisco is in the works

**Comment by lunkwill42** [comment]
Both subtasks have been closed, also closing this tracking issue.
